apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: react-native-web-webview
  description: React Native for Web implementation of RN's WebView
spec:
  type: library
  lifecycle: production
  domain: frontend-apps
  system: frontend-app-framework
  owner: frontend-platform
